package acm_practica1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Maria S
 */
public class VisualParte1bOpcional extends javax.swing.JFrame {

    private List<Punto> listaCiudades;
    private String nombreTSP;
    private int talla;
    private final GeneraPuntos GP = new GeneraPuntos();
    private final Algoritmos1B TSP = new Algoritmos1B();

    public VisualParte1bOpcional() {
        initComponents();
        buttonGroup1.add(Button10);
        buttonGroup1.add(Button11);
        buttonGroup1.add(Button12);
        GP.rellenarPuntos(1, false);
        this.listaCiudades = GP.getListaPuntos();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        PrintStream printStream = new PrintStream(new CustomOutputStream(texto));
        System.setOut(printStream);
        System.setErr(printStream);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                dibujarPuntos(g, TSP.calcularSolucionOptima(listaCiudades), this.getWidth(), this.getHeight());
            }
        };
        textoScroll = new javax.swing.JScrollPane(texto);
        texto = new javax.swing.JTextPane();
        Button10 = new javax.swing.JRadioButton();
        Button11 = new javax.swing.JRadioButton();
        Button12 = new javax.swing.JRadioButton();
        ButtonGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        texto.setBackground(new java.awt.Color(255, 255, 255));
        textoScroll.setViewportView(texto);

        Button10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Button10.setText("10 Puntos");
        Button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button10ActionPerformed(evt);
            }
        });

        Button11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Button11.setText("11 Puntos");
        Button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button11ActionPerformed(evt);
            }
        });

        Button12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Button12.setText("12 Puntos");
        Button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button12ActionPerformed(evt);
            }
        });

        ButtonGenerar.setText("Generar");
        ButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(ButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(textoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Button10)
                        .addGap(36, 36, 36)
                        .addComponent(Button11)
                        .addGap(36, 36, 36)
                        .addComponent(Button12)
                        .addGap(74, 74, 74)
                        .addComponent(ButtonGenerar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(textoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGenerarActionPerformed
        listaCiudades.clear();  //vaciamos la lista antes de usarla
        System.out.println("TALLA: "+ talla);
        GP.rellenarPuntos(talla, false);
        this.listaCiudades = GP.getListaPuntos();
        TSP.mostrarSolucionOptima(listaCiudades);
        
        jPanel1.repaint();

    }//GEN-LAST:event_ButtonGenerarActionPerformed

    private void Button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button10ActionPerformed
        talla = 10;
    }//GEN-LAST:event_Button10ActionPerformed

    private void Button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button11ActionPerformed
        talla = 11;
    }//GEN-LAST:event_Button11ActionPerformed

    private void Button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button12ActionPerformed
        talla = 12;
    }//GEN-LAST:event_Button12ActionPerformed


    // Clase para redirigir la salida estándar al JTextPane
    private static class CustomOutputStream extends OutputStream {

        private JTextPane textPane;

        public CustomOutputStream(JTextPane textPane) {
            this.textPane = textPane;
        }

        @Override
        public void write(int b) {
            StyledDocument doc = textPane.getStyledDocument();
            Style style = textPane.getStyle(StyleContext.DEFAULT_STYLE);
            try {
                doc.insertString(doc.getLength(), String.valueOf((char) b), style);
            } catch (BadLocationException e) {
                e.printStackTrace();
            }
        }
    }

    private static void dibujarPuntos(Graphics g, List<Punto> ruta, int panelAncho, int panelAlto) {

        double maxX = ruta.stream().mapToDouble(Punto::getX).max().orElse(0);
        double maxY = ruta.stream().mapToDouble(Punto::getY).max().orElse(0);

        double factorEscala = Math.min(panelAncho / maxX, panelAlto / maxY);

        // Dibujar líneas rojas entre los puntos de la ruta
        if (ruta != null && !ruta.isEmpty()) {
            g.setColor(Color.RED);
            for (int i = 0; i < ruta.size() - 1; i++) {
                Punto punto1 = ruta.get(i);
                Punto punto2 = ruta.get(i + 1);

                int x1 = (int) (punto1.getX() * factorEscala);
                int y1 = (int) (punto1.getY() * factorEscala);
                int x2 = (int) (punto2.getX() * factorEscala);
                int y2 = (int) (punto2.getY() * factorEscala);

                g.drawLine(x1, y1, x2, y2);
            }
            //linea entre el primero y el ultimo
            int primerX = (int) (ruta.get(0).getX() * factorEscala);
            int primerY = (int) (ruta.get(0).getY() * factorEscala);
            int ultimoX = (int) (ruta.get(ruta.size() - 1).getX() * factorEscala);
            int ultimoY = (int) (ruta.get(ruta.size() - 1).getY() * factorEscala);

            g.drawLine(primerX, primerY, ultimoX, ultimoY);
        }

        for (int i = 0; i < ruta.size(); i++) {
            Punto punto = ruta.get(i);
            int x = (int) (punto.getX() * factorEscala);
            int y = (int) (punto.getY() * factorEscala);

            if (i == 0) {
                g.setColor(Color.BLUE);     // Cambiar el color del primer punto a azul
            } else if (i == ruta.size() - 1) {
                g.setColor(Color.YELLOW);   // Cambiar el color del ultimo punto a amarillo
            } else {
                g.setColor(Color.BLACK);    // Restablecer el color a negro para los demás puntos
            }
            g.fillOval(x, y, 5, 5);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Button10;
    private javax.swing.JRadioButton Button11;
    private javax.swing.JRadioButton Button12;
    private javax.swing.JButton ButtonGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane texto;
    private javax.swing.JScrollPane textoScroll;
    // End of variables declaration//GEN-END:variables
}
